services:
  postgres:
    image: postgres:16
    container_name: saldium-postgres

    restart: unless-stopped

    env_file:
      - .env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - saldium-network

  api:
    image: saldium-api:latest

    build:
      context: .
      dockerfile: Dockerfile

    container_name: saldium-api

    restart: unless-stopped

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - saldium-network

volumes:
  postgres_data:

networks:
  saldium-network:
    driver: bridge